docs: update spark and mapreduce port range docs
TOSIT-IO/TDP pull request #28
Opened 2022-06-09 08:23 UTC by DanielJohnHarty

I made these updates yesterday but pushed them directly to master (my mistake).
I've made some edits today on this branch to improve yesterday's pushed content:
- Removed instances of triple space throughout the doc
- Reformatted the spark multiple properties as `Sources` + a list
- Added more context/notes to the entries in a similar vein to t the notes in the inventory files in `tdp-collection`

2022-06-09 10:50 UTC, wdavidw requested changes

2022-06-09 10:50 UTC, wdavidw commented on docs/ports.md
> +  - ApplicationMaster
Since this is limited to MapReduce, I propose to reformulate the title to "MapReduce ApplicationMaster".

2022-06-09 10:50 UTC, wdavidw commented on docs/ports.md
> +    Ephemeral HTTPS ports are opened by each ApplicationMaster. The `tdp-collection` default port range is unrestricted but is parameterized in the `tdp_var_defaults/hadoop/hadoop.yml` inventory file
Instead of ", not spark*.", use "*. In the case of Spark, refer to the Spark Driver port documentation, such as the `spark.driver.port` property".

2022-06-10 08:54 UTC, leopaul36 approved these changes

2022-06-10 08:55 UTC, rpignolet approved these changes

2022-06-10 09:38 UTC, wdavidw requested changes
Since Spark 2 and Spark 3 are identical, no need for two distinct sections. It introduces more confusion than clarity. Could you merge the two into "Spark 2 and 3".

2022-06-13 07:57 UTC, DanielJohnHarty commented
Spark2 and Spark3 entries have been merged now @wdavidw

2022-07-30 20:32 UTC, wdavidw approved these changes

2022-07-30 20:33 UTC, merged